AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AltairVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.8.0.0/24
      Tags:
      - Key: Name
        Value: AltairVPC
  AltairInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: Altair-IGW
  AltairAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref AltairVPC
      InternetGatewayId: !Ref AltairInternetGateway
  AltairRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AltairAttachGateway
    Properties:
      VpcId: !Ref AltairVPC
      Tags:
      - Key: Name
        Value: Altair-RouteTable
  AltairRoute:
    Type: AWS::EC2::Route
    DependsOn: AltairAttachGateway
    Properties:
      RouteTableId: !Ref AltairRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref AltairInternetGateway
  AltairSubnet:
    Type: AWS::EC2::Subnet
    DependsOn: AltairAttachGateway
    Properties:
      CidrBlock: 10.8.0.0/25
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref AltairVPC
      Tags:
      - Key: Name
        Value: Altair-Subnet
      - Key: Environment
        Value: Staging
  AltairSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AltairSubnet
      RouteTableId: !Ref AltairRouteTable
